= Solri
Wei Tang <wei@that.world>
:license: CC-BY-SA-4.0
:license-code: Apache-2.0
:order: 4

[meta=description]
Solri is a blockchain experiment that tries to bring Substrate style
on-chain governance for Proof of Work.

In particular, the design goal is to:

* Become a **pure** coin, in most possible aspects that blockchain
  community cares about. This includes having **no premine** and
  establishes **fair launch**.
* Use well-established **Proof of Work** consensus algorithm, and at
  the same time, allows it to change to either become ASIC-friendly or
  ASIC-resistent.
* Most essential functions of the blockchain is coded into
  **WebAssembly** runtime. This makes it so that the blockchain can
  evolve and upgrade features **without hard fork**. In fact, we aim
  to never conduct any hard fork!
* Have clear and simple **specification** to make supporting multiple
  implementations easier.
* Be **stateless**. To fully verify a new block, you will only need
  the parent block together with the parent block's runtime
  output. This reduces the bare minimal storage requirement for full
  node to nearly zero. In practice, clients can selectively choose to
  only store states it cares about.

== Resources ==

* *link:https://github.com/solri/solri[Reference Implementation]*:
   Draft reference implementation of Solri.
* *link:https://riot.im/app/#/room/#solri:matrix.org[Matrix
  Community]*: Chat room hosted on Matrix.
* *link:https://discord.gg/DZbg4rZ[Discord Community]*: Chat room
  hosted on Discord.
