= Ethereum Compatibility Layer for Substrate
Wei Tang <@sorpaas>
:license: CC-BY-SA-4.0

[meta=description]
This provides a description of the compatibility layer built on
Substrate to run unmodified Ethereum dapps.

The goal of Ethereum compatibility layer is to be able to:

* Run a *normal* web3 application via the compatibility layer, using
  local nodes, where an extra bridge binary is acceptable.
* Be able to import state from Ethereum mainnet.

== Scope

=== Types of Dapps

We consider three different types of dapps:

* *Dapps without private keys*: those dapps do not handle private keys. They
   relies on `eth_sendTransaction` and expect the RPC node to handle
   keys.
* *Dapps with private keys*: those dapps handle private keys
   internally, and will instead use `eth_sendRawTransaction`.
* *Specialized dapps*: dapps with special functionalities. Those
   include ones that relies heavily on internal Ethereum
   implementation details. An example would be a decentralized mining
   pool contract.

The goal of the Ethereum compatibility layer is to support dapps with
or without private keys. We ignore the case for specialized dapps as
it is expensive to emulate subtle details of Ethereum
implementations. Any method that can support _dapps with private keys_
will also support _dapps without private keys_, but not vice versa. In
appendix, an alternative method is provided that only handles _dapps
without private keys_, but is simpler.

== Runtime

=== EVM Pallet

The module would handle the essence of EVM invocations, and is
implemented as `pallet-evm`.

==== External State

NOTE: This section describes something that has not yet been
implemented.

The pallet should be able to delegate state fetching (both accounts
and storage) via an external trait.

[source,rust]
----
trait ExternalBackend {
  type Error;

  fn account(
    &self,
    address: H160
  ) -> Result<(evm::backend::Basic, Vec<u8>), Self::Error>;
  fn storage(&self, address: H160, index: H256) -> Result<H256, Self::Error>;
}
----

When state is accessed, we first check whether internal state exists,
if so, use it. If not, fetch the value via the external trait. State
are always committed internally.

Note the difference compared with internal state that the access can
fail. If the access failed, discard all current EVM changes, consume
all gases, and exit. This is the same as an "unsupported" error in
`rust-evm`.

=== Block Processing Emulatiom Pallet

NOTE: This section describes something that has not yet been
implemented.

A separate pallet module `pallet-ethereum` is required to emulate the
full block processing part. This pallet has two main functionalities:

* Store the pin of state import, if any.
* Store mapping of secp256k1 keys to sr25519 keys.
* Delegate call the EVM pallet, so that separate transaction and
  receipt information can be generated.

The module will have at least the following extrinsics:

* `proveState`: it takes an object returned by `eth_getProof`, and
  commit the returned state.
* `transact`: take a full Ethereum transaction, decode the RLP object,
  and delegate the call to EVM pallet. It then gathers the logs and
  receipts, and store them. There can be a whitelist of secp256k1 keys
  to sr25519 keys, or it can be configured to skip secp256k1 signature
  verification at all.

== RPC

=== Internal RPC Module

NOTE: This section describes something that has not yet been
implemented.

The RPC module talks with `pallet-ethereum`. The blocks are emulated
as follows:

* Take Substrate's state root as the Ethereum's state root.
* Take each block's transaction and receipt root from
  `pallet-ethereum`.
* Value of `difficulty`, `extraData`, `gasLimit`, `gasUsed`, `uncles`
  and other PoW-specific values are either none, default, or can be
  configured to be a constant.

=== RPC Bridge

NOTE: This section describes something that has not yet been
implemented.

The bridge talks with both the internal RPC module, and an Ethereum
node. It is the endpoint that exposes Ethereum-compatible RPC
methods. The Ethereum node is either required to be archive, or
static. Either way, it should always have the state root pinned at
Substrate's genesis block available.

The bridge's job is to intercept any transactions sent from dapp, and
accomodate it with an extra `proveState` extrinsic call that actually
commits state.

The bridge also directly talks with `rust-evm` for anything that does
not need to write on-chain. For example, `eth_estimateGas`.

== Workflow

To port a dapp initially designed for Ethereum mainnet, the following
steps are needed:

* Pick a block on Ethereum mainnet, where the dapp is "frozen". Write
  down the block's state root.
* Commit the state root in Substrate's genesis file to
  `pallet-ethereum`.
* Start the internal RPC module and the RPC bridge.
* Now the dapp can be used as normal.
