= Effective total supply
Wei Tang <wei@that.world>
:license: CC-BY-SA-4.0
:license-code: Apache-2.0

[meta="description"]
Effective total supply is a concept of total supply with consideration of fee
market. Kulupu currently has an effective total supply of 75 million KLP, after
referendum #26 has passed.

Kulupu implements fee market, which is a method to have more predictable
transaction fees. With this method, the _base_ transaction fees are burned
instead of paid to miners. Miners only retain the _tips_. Burning the base fee
is important as it avoids giving miners incentives to create artifical
transactions to manipulate the fee.

Kulupu also implements a treasury and miner reward taxation system. With this implementation, the treasury funding gets burned every spending cycle.

In a proof of work blockchain, a popular theme is total supply, in which block
rewards initially dominate, and then gradually switch to a fee only system.
However, with burning methods like fee market and treasury spending, a direct
translation of total supply will result in deflation.

== Definition

Instead of a definite total supply, here we propose a concept called **effective
total supply**. Effective total supply is the actual eventual total supply of a
blockchain, with considerations of fee market and other coin burning methods.

== Reaching fixed effective total supply

To reach fixed effective total supply, we assume normal usage of Kulupu
blockchain. That is, each block is on average half full of its block weight
limit. A block half full would burn 8 KLP. As a result, any emission scheme with
eventual tail emission of equal or less than 8 KLP can be considered to have
fixed effective total supply.

== Current schedule

The current reward schedule table is as follows. Note that the tail emission of
1.5 KLP is well below the estimated burn rate of 8 KLP, which will result in
deflation. However, the decmoracy module in Kulupu can always adjust the table
in the future, in order to improve the situation.

.Table Emission
|===
| Start block | Count | Reward |
| 0 (era 1) | 320000 | 60 |
| 0 (era 2) | 200000 | 60 |
| 200000 | 5600 | 54 |
| 205600 | 344400 | 30 |
| 550000 | 250000 | 24 |
| 800000 | 250000 | 21 |
| 1050000 | 250000 | 18 |
| 1300000 | 250000 | 15 |
| 1550000 | 250000 | 12 |
| 1800000 | 250000 | 9 |
| 2050000 | 250000 | 6 |
| 2300000 | 250000 | 3 |
| 2550000 | 250000 | 1.5 |
|===